# About the QRP {#sec-about-qrp}

## Type 1: Extract Information to Calculate Background Rates

The program identifies an exposure, outcome, or medical condition, and calculates the rate of that event in the SDD. Output includes the number of individuals with the exposure/outcome/medical condition, eligible members, and eligible member-days. Rates are reported overall and stratified by user-defined age group, sex, year, and year-month. An attrition table is also provided upon request.

[Continue reading about Background Rate Calculation](#sec-t1-backratecalc)

## Type 2: Extract Information on Exposures and Follow-up Time

The program identifies an exposure of interest, determines exposed time as either user-defined number of days after exposure initiation or based on drug dispensing days supply, and looks for the occurrence of HOIs during exposed time. Output metrics include number of exposure episodes and number of individuals, number of HOIs, and days at-risk. Events per person-day at risk are reported overall and stratified by user-defined age group, sex, year, and year-month. Incidence rate ratios (IRRs) can be calculated using two identified cohorts (e.g., exposed vs. active-comparator cohort). Unadjusted IRRs and IRRs adjusted by age group, sex, year, and Data Partner are reported upon request. An attrition table is also provided upon request.

The user also has the option to characterize cohorts with concomitant use of medical products and look for the occurrence of health outcomes of interest (HOI) using the Concomitant Use Tool. Users may also characterize multiple events within an episode of medical product use through use of the Multiple Events functionality and characterize overlap between two separate treatment episodes using the Overlap Tool.

The exposures and follow-up time cohort identification strategy is designed to be compatible with the PSA module. For this cohort identification strategy, the CIDA module will 1) extract covariates of interest during user-defined evaluation windows for the propensity score estimation model; and 2) output an analytic dataset containing the necessary information for the PSA module to execute.

## Type 3: Extract Information for a Self-controlled Risk Interval Design

The program identifies an exposure of interest, identifies a user-defined risk and control window relative to the exposure date, and examines the occurrence of HOIs during the risk and control windows. Output metrics include number of exposure episodes, exposed individuals, individuals with an HOI in the risk and/or control windows, and censored individuals, overall and stratified by user-defined age group, sex, year, year-month, and time-to-event in days. An attrition table is provided upon request.

## Type 4: Extract information for medical product use during pregnancy

The program identifies live births, computes pregnancy episodes based on those live birth events, and assesses the use of specific medical products both during pregnancy episodes and in a comparator group of individuals likely to not have delivered a live birth during the same time frame. Output includes the number of pregnancy episodes stratified by year, maternal age, and existence of a pregnancy duration code. Medical product use is reported for both pregnancy episodes and comparator episodes according to trimester of use, gestational week, maternal age, and calendar year of delivery.

The medical product use during pregnancy cohort identification strategy is designed to be compatible with the PSA module. When used with the PSA module, maternal and infant health outcomes of interest are evaluated. An exposure pregnant cohort and a comparator or unexposed pregnant cohort can be assessed. For this cohort identification strategy, the CIDA module will 1) extract covariates of interest during user-defined evaluation windows for the propensity score estimation model; and 2) output an analytic dataset containing the necessary information for the PSA module to execute.

## Type 5: Extract Information for Medical Product Utilization

The program identifies the 'first valid' exposure episode (i.e., the first episode during the query period that meets cohort entry criteria) as the index date, and then includes all subsequent exposure episodes. Output metrics include the number of patients, episodes, dispensings, and days supply by sex, age group and month of study start (for the first patient episode or all observed episodes during the query period); number of episodes by episode number, episode length, sex and age group, reason(s) for censoring; number of episode gaps by gap number, gap length, sex and age group.

While many options available in the CIDA module are specific to the cohort identification strategy employed, some are not. The next sections describe functionality common across strategies, and are followed by descriptions of functionality specific to the cohort identification strategy selected.

## Type 6: Extract Information on Manufacturer-level Product Utilization and Switching Patterns

The program identifies product groups by user-defined lists of product codes (e.g., NDCs) grouped together to represent distinct manufacturer-level products and then characterizes patterns of drug use. Output metrics include counts of users and dispensings, days supplied per dispensing, episode duration, as well as time to uptake. The CIDA module also performs a product switching analysis that evaluates patient-level switching behavior between manufacturer-level product groups.