## Type 1 File

The Type 1 File is optional and its specification is only required for a background rate calculation cohort identification strategy. Options include selecting the number of events an individual can contribute to the request,the number of days before index date to assess incidence criteria, whether to truncate enrollment at death date, and whether to output a table characterizing reason for censoring eligibility. @tbl-type1file-spec contains detailed specifications for this file.

+----------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Parameter                                    | Field Name        | Description                                                                                                                                                                                                                                                                                                                                 |
+:=============================================+:==================+:============================================================================================================================================================================================================================================================================================================================================+
| Name of Cohort                               | GROUP             | Standardized name used to differentiate cohorts.                                                                                                                                                                                                                                                                                            |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Note 1:** multiple cohorts can be defined within the same Type 1 File. In this case all cohorts are queried independently and results are reported separately and labeled using each GROUP name specified.                                                                                                                                |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Note 2:** GROUP is the primary key linking cohorts across input files; GROUP values must match (including case) between the TYPE1FILE and other input files.                                                                                                                                                                              |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Note 3:** GROUP value must begin with letter or underscore.                                                                                                                                                                                                                                                                               |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Note 4:** GROUP values must be lowercase.                                                                                                                                                                                                                                                                                                 |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Format:** SAS character \$40; no special characters (e.g., commas, periods, hyphens, spaces, etc.) allowed, and underscores must be used to mark spaces.                                                                                                                                                                                  |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Example:** insulin                                                                                                                                                                                                                                                                                                                        |
+----------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Allowed Number of Index Dates per Individual | T1COHORTDEF       | Indicates how many index dates an individual can contribute. Options include:                                                                                                                                                                                                                                                               |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | -   **01:** Cohort includes only the first valid index date per individual during the query period.                                                                                                                                                                                                                                         |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | -   **02:** Cohort includes all valid index dates per individual during the query period.                                                                                                                                                                                                                                                   |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Note 1:** T1COHORTDEF parameter is used in conjunction with the T1WASHPER variable (below) to define valid index date(s).\                                                                                                                                                                                                                |
|                                              |                   | \                                                                                                                                                                                                                                                                                                                                           |
|                                              |                   | **Format:** SAS character \$2\                                                                                                                                                                                                                                                                                                              |
|                                              |                   | **Example:** 01                                                                                                                                                                                                                                                                                                                             |
+----------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Type 1 Index Washout Period                  | T1WASHPER         | Length of washout period in days. The washout period is a period before an index date during which an individual cannot have evidence of index-defining criteria (see Cohort Codes File specification for additional details on index-defining criteria).                                                                                   |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Note 1 special case:** when T1WASHPER = missing the program requires ENRDAYS of continuous enrollment but only considers an exposure/event valid if, at index date, the member has no evidence of the exposure in their entire available enrollment history that meets coverage requirements (as specified in COVERAGE)                   |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Format:** Numeric                                                                                                                                                                                                                                                                                                                         |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Example:** 365                                                                                                                                                                                                                                                                                                                            |
+----------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Censor Enrollment at Evidence of Death       | CENSOR_DTH        | Indicates if enrollment should be censored based on death date. Allowable values are `Y` and `N`.                                                                                                                                                                                                                                           |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | Date of death can be determined two ways:                                                                                                                                                                                                                                                                                                   |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | 1.  Where `Discharge_Status` = `EX` in the SCDM Encounter table, date of death is set to discharge date.                                                                                                                                                                                                                                    |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | 2.  Using death date in the SCDM Death table for records where `Confidence` = `E`.                                                                                                                                                                                                                                                          |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Note 1:** in cases where a death date appears in both the Death and Encounter tables, the date from the Death table will be used.\                                                                                                                                                                                                        |
|                                              |                   | \                                                                                                                                                                                                                                                                                                                                           |
|                                              |                   | **Note 2:** censoring is implemented by restricting enrollment eligibility. Member eligibility is truncated at death date. Once a death date is observed, a member can no longer contribute eligible periods (even if they are observed in the data).\                                                                                      |
|                                              |                   | \                                                                                                                                                                                                                                                                                                                                           |
|                                              |                   | **Format:** SAS character \$1\                                                                                                                                                                                                                                                                                                              |
|                                              |                   | **Example:** Y                                                                                                                                                                                                                                                                                                                              |
+----------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Categories for Follow-up Time                | CENSOR_OUTPUT_CAT | Indicates ranges (in days) for stratification variable CENSDAYS_VALUE in \[RUNID\]\_censor_cida.sas7bdat output.                                                                                                                                                                                                                            |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Note 1:** leave blank if only continuous values of CENSDAYS_VALUE are desired. If this field is left blank, output stratified by CENSDAYS_VALUE in \[RUNID\]\_censor_cida will have one category that includes all values of CENSDAYS_VALUE.                                                                                              |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Note 2:** For each cohort in the TYPE1FILE, CENSOR_OUTPUT_CAT must specify the same value.                                                                                                                                                                                                                                                |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Format:** SAS character—length can vary                                                                                                                                                                                                                                                                                                   |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Example:** 0-364 365-729 730-1094 1095+                                                                                                                                                                                                                                                                                                   |
+----------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Output Denominator Indicator                 | OUTPUTDENOM       | Indicates whether to calculate denominator variables DENNUMPTS (number of patients eligible to have at least one index date) and DENNUMMEMDAYS (number of days that patients are eligible to have an index date).                                                                                                                           |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | Valid values are:                                                                                                                                                                                                                                                                                                                           |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | -   **Y:** DENNUMPTS and DENNUMMEMDAYS variables will be calculated and populated in \[RUNID\]\_t1_cida.sas7bdat.                                                                                                                                                                                                                           |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | -   **M:** DENNUMPTS variable will be calculated and populated in \[RUNID\]\_t1_cida.sas7bdat. DENNUNMEMDAYS variable will NOT be calculated and will be set to missing in \[RUNID\]\_t1_cida.sas7bdat.                                                                                                                                     |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | -   **N:** DENNUMPTS and DENNUMMEMDAYS variables will NOT be calculated and will be set to missing in \[RUNID\]\_t1_cida.sas7bdat.                                                                                                                                                                                                          |
|                                              |                   |                                                                                                                                                                                                                                                                                                                                             |
|                                              |                   | **Note 1:** if MINRXDAYS is specified as an inclusion/exclusion criterion, OUTPUTDENOM will be automatically set to N.\                                                                                                                                                                                                                     |
|                                              |                   | \                                                                                                                                                                                                                                                                                                                                           |
|                                              |                   | **Note 2:** When performing a Type 1 or 2 analysis that calculates denominators (e.g., eligible members and eligible member-days) and requesting stratifications, the CIDA module will only populate denominators for the pre-defined stratification variables (see Table 2 in the User-defined Strata Levels Lookup Table documentation).\ |
|                                              |                   | \                                                                                                                                                                                                                                                                                                                                           |
|                                              |                   | **Format:** SAS character \$1\                                                                                                                                                                                                                                                                                                              |
|                                              |                   | **Example:** Y                                                                                                                                                                                                                                                                                                                              |
+----------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: TYPE1FILE specification {#tbl-type1file-spec .responsive}

To read more about how Type 1 Queries work, please refer to [Type 1: Extract Information to Calculate Background Rates](#sec-type1-package). For information on other Types, please refer to @sec-about-qrp.